; --- MOTOROLA 6800 ASSEMBLY CIKTISI (FULL-STACK TINYSYS) ---

; --- Klavyeden Veri Okuma: READ LIMIT ---
	JSR READ
	STAA LIMIT

; --- Atama: SAYAC = 0 ---
	LDAA #0
	STAA SAYAC

; --- Pointer Atama: POINTER P = &GIZLI_VERI ---
	LDX #GIZLI_VERI     ; GIZLI_VERI adresini Index Register'a yukle

; --- Pointer ile Deger Degistirme: *P = 15 ---
	LDAA #15
	STAA 0,X

; --- DONGU (WHILE) BASLANGICI: WHILE SAYAC < LIMIT ---
L_WHILE_START_1 
	LDAA SAYAC
	CMPA LIMIT
	BGE L_WHILE_END_1 

; --- Toplama: SAYAC = SAYAC + 1 ---
	LDAA SAYAC
	ADDA #1
	STAA SAYAC

; --- KOSUL (IF) BASLANGICI: IF SAYAC == 15 ---
	LDAA SAYAC
	CMPA #15
	BNE L_ENDIF_1 

; --- Ekrana Yazdirma: PRINT SAYAC ---
	LDAA SAYAC
	JSR PRINT

; --- KOSUL (IF) BITISI ---
L_ENDIF_1 

; --- DONGU (WHILE) BITISI ---
	BRA L_WHILE_START_1 
L_WHILE_END_1 

